## VARIABLES ##
_MAKE_INCLUDE_PATH =
include $(_MAKE_INCLUDE_PATH)Variables.make

### TARGET VARIABLES ###
TARGET_EXT =

### SOURCE VARIABLES ###
INCLUDE_DIRS += 
SRC_FILES += 
LIB_DIRS += 
LIB_FLAGS +=
LIB_PROJECTS = 

### LANGUAGE VARIABLES ###
COMPILIER = g++
CPP_LANGUAGE = c++1z
PREPROCESSOR_MACROS =

## RULES ##
include $(_MAKE_INCLUDE_PATH)Rules.make
include $(_MAKE_INCLUDE_PATH)Default-Rules.make