PROJECT_DIR = $(CURDIR)/
PROJECT_NAME = $(notdir $(patsubst %/, %, $(dir $(PROJECT_DIR))))
SOLUTION_DIR = $(PROJECT_DIR)../

BIN_DIR_DEBUG = bin/Debug/$(OS_NAME)/$(PLATFORM_NAME)/
OBJ_DIR_DEBUG = obj/Debug/$(OS_NAME)/$(PLATFORM_NAME)/
OUT_DIR_DEBUG = $(PROJECT_DIR)$(BIN_DIR_DEBUG)
INT_DIR_DEBUG = $(PROJECT_DIR)$(OBJ_DIR_DEBUG)

BIN_DIR_RELEASE = bin/Release/$(OS_NAME)/$(PLATFORM_NAME)/
OBJ_DIR_RELEASE = obj/Release/$(OS_NAME)/$(PLATFORM_NAME)/
OUT_DIR_RELEASE = $(PROJECT_DIR)$(BIN_DIR_RELEASE)
INT_DIR_RELEASE = $(PROJECT_DIR)$(OBJ_DIR_RELEASE)

INCLUDE_DIRS += $(SOLUTION_DIR) $(PROJECT_DIR) $(SOLUTION_DIR)packages/